safe: false
lsi: false

rvm:
  - 2.4.1

name: Joshua Dowding
title: Joshua Dowding
description: Joshua Dowding's personal website, portfolio and blog.

author:
  twitter: Mordaval

url: https://joshdowding.github.io
baseurl: ""

destination: ./_site/

username: joshuadowding
repo: joshuadowding.io
branch: master

sudo: false

cache: bundler

permalink: pretty

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Rakefile
  - changelog.md
  - "*.Rmd"
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
  sass_dir: css
  style: compressed

include: ['_pages']
