title: Joshua Dowding's Portfolio
author: Joshua Dowding
description: Joshua Dowding's personal blog and portfolio.
lang: en_GB

url: https://jdowding.me
destination: ./_site/
permalink: /:year/:month/:day/:title.html
include: ['_pages']

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: /page:num/

sitemap: true

sass:
  sass_dir: css
  style: compressed
