title: Joshua Dowding's Portfolio
author: Joshua Dowding
description: Joshua Dowding's personal website, portfolio and blog.
lang: en_GB

url: https://joshdowding.github.io
destination: ./_site/
permalink: /:year/:month/:day/:title.html
include: ['_pages']

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5
paginate_path: /page:num/

sitemap: true

sass:
  sass_dir: css
  style: compressed
